//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int RowID { get; set; }
        public string Username { get; set; }
        public Nullable<int> Steps { get; set; }
        public Nullable<int> Heartrate { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
